### ISSUE TITLE
2021 release of EGSnrc reworking of job control causes issues with gzip egsdat files

### ISSUE THREAD

**Issue by MartinMartinov** [clrp-code/egs_brachy#21] opened 2021-09-29 17:31 UTC
Parallel job submission does not work when using gzip egsdat files.  Best guess so far: there's some authentication that happens when they are generated that creates issues because the file names end with egsdat.gz instead of egsdat...

Needs further investigation, recommend using the normal egsdat text format for now.

**Comment by mchamberland** [comment] 2022-08-07 00:41
Can confirm. Changes to EGS_Application and EGS_RunControl are causing the issue. They specifically look for the “.egsdat” extension. 

Thus can probably be resolved by re-implementing those functions in egs_brachy to account for gzip.

**Comment by mchamberland** [comment] 2023-01-03 19:51
@MartinMartinov  I think I have a fix, but I can't reproduce the issue to confirm. Any chance you can still reproduce this issue? If so, can you try the fix in a2e4fef10e1b424610240ddaaf3d4d12d839efc5 or give me direction on how to reproduce?

Currently, I'm just using my laptop and the egs-parallel script to submit directly to my CPU and I can use the URCO option without any problem.

**Comment by MartinMartinov** [comment] 2023-01-05 01:33
Hi Marc, unfortunately the issue was on a Western University computer I no longer have access to.  The fix looks good though, so I would probably recommend closing and someone else can bring it up if they encounter it.

**Comment by mchamberland** [comment] 2023-01-06 02:11
Thanks, @MartinMartinov! I will merge and close. My pull request at least fixes the counting of jobs still running, so there's that.

**Closed** 2023-01-06 02:12 UTC
Labels: bug
